Update boulder and its setup (#6)
Update boulder release to test against a more recent version.
`release-2016-07-14` does not work due to
"E135725 boulder-ca [AUDIT] Panic caused by err: runtime error:
invalid memory address or nil pointer dereference".

For the current travis tursty images we must declare that we
need rabbitmq as service.

We build with go 1.6 - we got some compilation errors with
go 1.5.

We use prebuild debs for protobuf (from 5-james-t/protobuf-ppa).
We reduces the testing time by 1-2 minutes, as we no longer need
to compile protobuf ourself during setup.